### ISSUE TITLE
Woocommerce 的超商取貨付款 新增物流訂單按鈕沒有出現

### ISSUE THREAD

**Issue by ChuyuHsu** [ECPay/WooCommerce_PHP#1]
php 中產生按鈕的那段 if {} block 執行不正常
沒有得到預期結果

**Comment by AllennChang** [comment]
感謝您的發問,通常未出現按鈕是輸入的欄位值有錯誤,若有進一步的問題,歡迎您來信發問,感謝 techsupport@greenworld.com.tw
