### ISSUE TITLE
（物流）新增後台列印超商快遞單

### ISSUE THREAD

**Issue by robert1112** [ECPay/WooCommerce_PHP#2]
您好，目前店家在WC後臺取號後，沒辦法直接列印快遞單，這樣造成店家很大不便！原因是店家必須->登入綠界後台->找到相對應訂單->列印。（超時的話，再重新登入綠界）
之前我們有寫入這功能，但是這次你們改版後，我們又需要重寫。是否可以把這件事情排入最優先呢？感謝。

**Comment by AllennChang** [comment]
您好，您的反應，我們已回饋給開發團隊研究，感謝提供

**Comment by robert1112** [comment]
您好，我們已經把這功能上傳到PULL REQUEST上了，也跟您們資訊副總聯絡過了，如果可以的話再Merge到Master。感謝您～

**Comment by AllennChang** [comment]
您好, 您提供的功能目前已完成合併,正在進行測試,若沒問題,近期會提供釋出

**Comment by AllennChang** [comment]
https://github.com/ECPay/WooCommerce_PHP/releases/tag/v1.1.0816
你的功能我們己經釋出在v1.1.0816 版本,若有任何問題,請再跟我們反應, 謝謝您
